// <auto-generated />
namespace KnockoutsBoxing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedimagetitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedimagetitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201710201225124_addedimagetitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
